variables:
  GIT_STRATEGY: clone
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

stages:
 - test

test:
 stage: test
 image: debian:buster
 script:
  - apt update
  - apt -y install default-jdk ant ivy git curl
  - git submodule init
  - git submodule update
  - mkdir lib
  - ant fetch-metrics-lib
  - ant -lib /usr/share/java resolve
  - ant test
  - ant checks
